resolver: lts-14.27

packages:
- purescheme-ssd-core
- purescheme-ssd-wai
- purescheme-ssd-wai-forms
- purescheme-ssd-reflex
- purescheme-ssd-reflex-forms

extra-deps:
- reflex-0.6.4
- reflex-vty-0.1.3.0
- constraints-extras-0.3.0.2
- dependent-map-0.3
- dependent-sum-0.6.2.0
- monoidal-containers-0.6.0.1
- patch-0.0.3.1
- ref-tf-0.4.0.2
- witherable-0.3.1
- reflex-basic-host-0.2.0.1
- purescheme-wai-routing-core-0.1.0.0
